# Generated by Django 4.1 on 2022-08-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0003_alter_project_creator_alter_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('priority', models.IntegerField(default=1, verbose_name='اولویت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project', verbose_name='پروژه')),
            ],
        ),
    ]
