# Generated by Django 4.1 on 2022-08-06 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice', verbose_name='توضیحات صوتی')),
                ('possible_time', models.TimeField(verbose_name='زمان تخمینی ')),
                ('main_time', models.TimeField(verbose_name='زمان حساب شده ')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='creator_task', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
            ],
        ),
    ]
