# Generated by Django 4.1 on 2022-08-05 23:07

from django.db import migrations, models
import extentions.check_value


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'DeActive'), (2, 'Active'), (3, 'Fail'), (4, 'Done')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='', validators=[extentions.check_value.limit_file_size], verbose_name='تصویر'),
        ),
    ]
