# Generated by Django 4.1 on 2022-08-06 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extentions.check_value


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0002_project_status_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='Project', validators=[extentions.check_value.limit_file_size], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'غیرفعال'), (2, 'فعال'), (3, 'رد شده'), (4, 'انجام شده')], default=1, verbose_name='وضعیت'),
        ),
    ]
