# Generated by Django 4.1 on 2022-08-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('solution', models.CharField(max_length=255, verbose_name='راه حل')),
            ],
        ),
    ]
